### ISSUE TITLE
Linchpin provisioning using up restendpoint

### ISSUE THREAD

**Issue by samvarankashyap** [CentOS-PaaS-SIG/restylinchpin#29]
The current issues concern itself provisioning workspaces created by linchpin
command line for provisioning is
```
 linchpin up 
```
an example request is as follows:

```
note: This API spec is subjected to change due to the fact that it would be eventually replaced by linchpin API. Further, it is subjected to changes when database integration happens.
```

endpoint:
/up/
methodtype: POST

request:
{
"name": "workspacename/pinfilename",
provision_type: "workspace",
 --> value can be either pinfile or workspace
}

in addition to existing parameters make sure your support other command line options.
please make sure you support other command line options except for destination. Since the destination is currently pre-configured

```
  -r, --run-id run_id             Idempotently provision using `run-id` data
                                  NOTE: This argument is mutually exclusive
                                  with  arguments: [tx_id].
  -t, --tx-id tx_id               Provision resources using the Transaction ID
                                  (tx-id) NOTE: This argument is mutually
                                  exclusive with  arguments: [run_id].
  --inventory-format, --if INVENTORY_FORMAT
                                  Inventory format cfg/json
  --ignore-failed-hooks, --ifh    Ignores failed hooks
  --no-hooks, --nh                Do not run hooks
  -h, --help                      Show this message and exit.
```

response:
{
id: "idofworkspace", 
"status": "workspace provisioned successfully"
"inventory": "contents_of_latest_inventory_generated_in_inventoryfolder",
"latest": "contents_of_linchpin.latest_file_in_resource_folder"}
}

If the workspace does not exist we need to return a message "workspace does not exist".

**Comment by Dannyb48** [comment]
If a user specifies type of pinfile, is it a reference to the actual pinfile file on disk, or can it be a json of the contents of the pinfile?

**Comment by samvarankashyap** [comment]
@Dannyb48 
Pinfile would be accepted as a json.
